added the file of data indexing, replication, and sharding
flashreads/blogs pull request #236
Opened 2022-10-23 11:39 UTC by Pragya2056

A file for data indexing, replication, and sharding. 
#233

2022-10-23 15:18 UTC, ZoranPandovski requested changes
Loosk grea, please just add the metadata as in the example https://raw.githubusercontent.com/flashreads/blogs/master/template.md

2022-10-23 15:45 UTC, Pragya2056 commented
I made the change

2022-10-23 15:45 UTC, Pragya2056 commented
@ZoranPandovski 
Please review once again

2022-10-23 18:29 UTC, natemago approved these changes

2022-10-24 14:54 UTC, natemago approved these changes

2022-10-24 14:54 UTC, merged